// =============================================================================
// PART A — LOAD WASM  (Sentry @sentry/wasm cares about this part)
// =============================================================================
//
//   maze.js   → Emscripten glue (generated by `make`, don't edit)
//   maze.wasm → your C++ game, compiled to WebAssembly
//
// Sentry needs a real URL on the wasm file (called code_file), e.g.
//   http://localhost:8080/web/maze.wasm
//
//   ✅  WebAssembly.instantiateStreaming(fetch(WASM_URL), imports)
//   ❌  fetch → arrayBuffer → WebAssembly.instantiate  (no URL kept)
//   ❌  wrong Content-Type (must be application/wasm)
//   ❌  wasm built without --build-id (see Makefile)
//
// Later: init Sentry with wasmIntegration() BEFORE loadWasm() runs.
//        It patches instantiateStreaming and reads response.url automatically.

const createMazeModule = globalThis.createMazeModule;
const WASM_URL = new URL('maze.wasm', import.meta.url).href;

async function loadWasm() {
  if (typeof createMazeModule !== 'function') {
    throw new Error('maze.js missing — run `make`, then hard-refresh');
  }

  const mod = await new Promise((resolve, reject) => {
    createMazeModule({
      instantiateWasm(imports, emscriptenReady) {
        WebAssembly.instantiateStreaming(fetch(WASM_URL), imports)
          .then(({ instance }) => {
            console.log('wasm loaded', { url: WASM_URL, instance });
            emscriptenReady(instance);
          })
          .catch(reject);
      },
    })
      .then(resolve)
      .catch(reject);
  });

  return mod;
}

// =============================================================================
// PART B — RUN GAME  (normal browser JS; unrelated to Sentry wasm setup)
// =============================================================================
//
// Flow each frame:  step_game() → render_frame() → copy pixels to canvas
// C++ functions are on `mod` with a _ prefix (Emscripten convention).

const canvas = document.getElementById('screen');
const ctx = canvas.getContext('2d');
const status = document.getElementById('status');
const hud = document.getElementById('hud');
const winOverlay = document.getElementById('win-overlay');

const KEYS = new Set([87, 65, 83, 68, 37, 38, 39, 40]); // WASD + arrows

let mod = null;
let imageData = null;
let lastTime = 0;
let level = 1;

function initGame(seed, nextLevel = level) {
  for (const code of KEYS) {
    mod._handle_key(code, 0);
  }
  level = nextLevel;
  mod._init_game(seed, level);
  winOverlay.classList.add('hidden');
  lastTime = 0;
  updateHud();
}

function updateHud() {
  if (mod._game_won()) {
    winOverlay.classList.remove('hidden');
    hud.textContent = `Level ${mod._get_level()} cleared`;
    status.textContent = 'Next level or regenerate';
    return;
  }
  hud.textContent =
    `Level ${mod._get_level()} · WASD / arrows · Keys ${mod._player_key_count()}/${mod._keys_required()} · exit bottom-right`;
}

function drawFrame() {
  mod._render_frame();
  const w = mod._get_width();
  const h = mod._get_height();
  const ptr = mod._get_pixel_buffer_ptr();
  const bytes = w * h * 4;
  const pixels = mod.HEAPU8.subarray(ptr, ptr + bytes);

  if (!imageData || imageData.width !== w) {
    imageData = ctx.createImageData(w, h);
  }
  imageData.data.set(pixels);
  ctx.putImageData(imageData, 0, 0);
  updateHud();
}

function loop(now) {
  const dt = lastTime ? now - lastTime : 0;
  lastTime = now;
  if (!mod._game_won()) {
    mod._step_game(dt);
  }
  drawFrame();
  requestAnimationFrame(loop);
}

function onKey(event, down) {
  if (!KEYS.has(event.keyCode)) {
    return;
  }
  event.preventDefault();
  mod._handle_key(event.keyCode, down ? 1 : 0);
}

// =============================================================================
// START
// =============================================================================

async function start() {
  try {
    mod = await loadWasm();
    initGame((Math.random() * 0x7fffffff) | 0, 1);
    canvas.width = mod._get_width();
    canvas.height = mod._get_height();
    status.textContent = `Running ${canvas.width}×${canvas.height}`;

    window.addEventListener('keydown', (e) => onKey(e, true));
    window.addEventListener('keyup', (e) => onKey(e, false));
    document.getElementById('regenerate').addEventListener('click', () =>
      initGame((Math.random() * 0x7fffffff) | 0, level),
    );
    document.getElementById('next-level').addEventListener('click', () =>
      initGame((Math.random() * 0x7fffffff) | 0, level + 1),
    );
    requestAnimationFrame(loop);
  } catch (err) {
    console.error(err);
    status.textContent = `WASM load failed: ${err.message}`;
  }
}

start();
